# Generated by Django 3.2.16 on 2022-12-19 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ad61a723-4304-4614-b0d7-9124ba843a0c'), primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=13)),
            ],
        ),
    ]
