# Generated by Django 3.2.16 on 2022-12-19 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6bbf5f8-9301-4c81-b332-a2a97fa6daac'), primary_key=True, serialize=False),
        ),
    ]
