# Generated by Django 3.2.16 on 2023-01-02 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0007_auto_20221229_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='labouratorist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountant',
            name='accountant_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labouratorist',
            name='labouratorist_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='nurse_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pharmacist_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
