# Generated by Django 3.2.16 on 2023-01-02 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0008_auto_20230102_1505'),
        ('Functionality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_price', models.CharField(blank=True, max_length=10, null=True)),
                ('medicine_quantity', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbank_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MedicineSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinesales_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('datetime', models.CharField(blank=True, max_length=100, null=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginSystem.accountant')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginSystem.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionality.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginSystem.patient')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginSystem.pharmacist')),
            ],
        ),
    ]
